### ISSUE TITLE
Let password be passed as a command-line argument

### ISSUE THREAD

**Issue by AgeOfMarcus** [degaart/emocrypt#2]
Add an option to take password from argument (eg: --password test), instead of prompting stdin.

**Comment by degaart** [comment]
This is a bad idea. The password will be written to your shell's history file. If the encryption takes a long enough time, the password could also be shown in the output of `ps`.

**Comment by AgeOfMarcus** [comment]
> This is a bad idea. The password will be written to your shell's history file. If the encryption takes a long enough time, the password could also be shown in the output of `ps`.

That's your opinion. At least let it be an option. You can warn users if you want about the dangers of passing it in as an argument but if I am running it from a secure system, without shell history, it should be **my choice** if I want to pass the pass as an arg.

I'm building an API that uses this program, and I can't use stdin.

Literally no one else refuses to make this an option. I'll fork your code if I have to.

**Comment by degaart** [comment]
> I'm building an API that uses this program

Why bother shelling out to this shitty program at all. Compile emocrypt using the cmake flag `-DBUILD_SHARED_LIBS=ON`. Once compiled, you'll get a `libcommon.so` file containing encrypt/decrypt functions. All you have to do is then to call the functions `ec::encrypt` and `ec::decrypt` using FFI from whatever language you're building your API with.

This has much better performance than executing an external program and is more stable.

> Literally no one else refuses to make this an option.

Openssh refuses. Ever wonder why you cannot provide a password as an argument to `ssh`. That's why.

> I'll fork your code if I have to

Sir, this is github. You're supposed to fork

**Comment by degaart** [comment]
Fixed in version 1.4

**Comment by AgeOfMarcus** [comment]
Hi I am sorry for my behavior in the comments, I was having a rough day. I've just never had to work with libraries like that, I'm a pythonista at heart. 

Edit: also i think your code is very cool, using emojis to encrypt data sounds cool to me, added obscurity!

**Comment by degaart** [comment]
It's ok. You can use the newly added `--password` option. But keep in mind the security implications
